version: '3'
services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: always
    environment:
      SA_PASSWORD: c0dingblocks!
      ACCEPT_EULA: Y
    volumes:
      - mssqlvolume:/var/opt/mssql/data
      - ./bk:/var/opt/mssql/backup
    ports:
      - '1533:1433'
volumes:
    mssqlvolume:

